# Generated by Django 5.1.1 on 2024-10-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='last_login',
            field=models.DateField(blank=True, null=True),
        ),
    ]
