# Generated by Django 5.1.1 on 2024-10-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='topic_names',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total_downloads',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total_logins',
            field=models.IntegerField(null=True),
        ),
    ]
