# Generated by Django 5.1.1 on 2024-10-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_stats_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='last_login',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
