# Generated by Django 5.2.1 on 2025-05-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_stats_topic_names_alter_stats_total_downloads_and_more'),
        ('users', '0003_alter_stats_last_login'),
        ('users', '0007_rename_user_name_profile_user'),
    ]

    operations = [
    ]
